services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./init.groovy.d:/var/jenkins_home/init.groovy.d
      - ./plugins.txt:/usr/share/jenkins/ref/plugins.txt
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/libexec/docker/cli-plugins:/usr/libexec/docker/cli-plugins
    entrypoint: >
      bash -c "
      jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt &&
      exec /usr/bin/tini -- /usr/local/bin/jenkins.sh
      "
    restart: unless-stopped

volumes:
  jenkins_home: